# Site settings
title: Datos Públicos @ INMEGEN
email: rgarcia@inmegen.gob.mx
description: > # this means to ignore newlines until "baseurl:"
  Como parte de la iniciativa por el acceso público a datos,
  y para mejor reproducibilidad de resultados, el Instituto
  Nacional de Medicina Genómica brinda acceso a esta colección
  de datos.
baseurl: "/opendata" # the subpath of your site, e.g. /blog/
url: "http://ddt-inmegen.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: DDT-INMEGEN

# Build settings
markdown: kramdown
